[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "todo_app_jabessette40
version = "0.0.1"
authors = [
  { name="Jeff Bessette", email="jabessette25@gmail.com" },
]
description = "A ToDo list package."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jabessette40/TO_DO"